# Generated by Django 3.0.dev20190125164321 on 2019-03-17 01:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position_preference', models.CharField(max_length=50, null=True)),
                ('location_preference', models.CharField(max_length=50, null=True)),
                ('education', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('job_title', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('job_description', models.TextField()),
                ('job_description_words', models.TextField()),
                ('min_education', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_name', models.CharField(max_length=25)),
                ('resume_file', models.FileField(upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_jobs.AppUser')),
            ],
            options={
                'unique_together': {('username', 'resume_name')},
            },
        ),
        migrations.CreateModel(
            name='UserApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25, null=True)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smart_jobs.JobApplications')),
                ('resume_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='smart_jobs.Resumes')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_jobs.AppUser')),
            ],
            options={
                'unique_together': {('username', 'job_title')},
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_jobs.JobApplications')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_jobs.AppUser')),
            ],
            options={
                'unique_together': {('username', 'job_title')},
            },
        ),
    ]
