# Generated by Django 3.0.dev20190125164321 on 2019-03-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplications',
            name='word_cloud',
            field=models.ImageField(default=None, upload_to='documents/wordcloud/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resumes',
            name='resume_file',
            field=models.FileField(upload_to='documents/resumes/'),
        ),
    ]
