# Generated by Django 2.1.7 on 2019-03-17 05:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resumes',
            unique_together={('username', 'resume_name')},
        ),
        migrations.AlterUniqueTogether(
            name='userapplications',
            unique_together={('username', 'job_title')},
        ),
    ]
