# Generated by Django 3.0.dev20190125164321 on 2019-03-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='location_preference',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
