# Generated by Django 2.1.7 on 2019-03-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumes',
            name='resume_file',
            field=models.FileField(upload_to='documents/resumes/'),
        ),
    ]
