# Generated by Django 3.0.dev20190125164321 on 2019-03-16 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smart_jobs', '0002_appuser_location_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
