# Generated by Django 2.1.7 on 2019-03-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_jobs', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
